     ;---------------------------------------------------
;WRITE A PROGRAM THAT ROTATES THE ELEMENTS OF THE ARRAY 
;ARR DB 1, 2, 3, 4, 5 ONE POSITION TO THE RIGHT.
;---------------------------------------------------  

.MODEL SMALL
.STACK 100H

.DATA
N DW 5
ARR DB 1, 2, 3, 4, 5
TEMP DB ?
LAST DB ?

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    ; STORE THE LAST ELEMENT SEPARATELY, AS IT WILL BE MOVED TO THE FIRST POSITION LATER.
    
    MOV CX,N
    DEC CX
    MOV SI,CX
    MOV BL,ARR[SI]
    MOV LAST,BL

    ; INITIALIZE TEMP WITH THE FIRST ELEMENT TO START ROTATION.
    
    MOV SI,0
    MOV BL,ARR[SI]
    MOV TEMP,BL
    INC SI

    ; SHIFT ALL ELEMENTS ONE POSITION TO THE RIGHT.
    ; LOOP STORES THE PREVIOUS VALUE IN THE CURRENT INDEX.
    
    FOR:
    MOV AL,TEMP
    MOV BL,ARR[SI]
    MOV TEMP,BL
    MOV ARR[SI],AL

    INC SI
    LOOP FOR

    ; PLACE THE LAST ELEMENT (PREVIOUSLY SAVED) AT THE FIRST POSITION.
    
    MOV BL,LAST
    MOV ARR[0],BL

    ; DISPLAY THE ROTATED ARRAY.
    
    MOV CX,N
    MOV SI, 0
    
    MOV AH,2
    PRINT:
    MOV DL,ARR[SI]
    ADD DL,48
    INT 21H
    MOV DL,32
    INT 21H

    INC SI
    LOOP PRINT

    ; PROGRAM TERMINATION.
    
    EXIT:
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN